### ISSUE TITLE
Bounty Time

### ISSUE THREAD

**Issue by neonnoon** [neonnoon/nodejs-goof#3]
Someone has offered USD 200 via Snyk Bounty to fix this issue.

See https://security.snyk.io/vuln/npm:adm-zip:20180415

**Comment by zhyd1997** [comment]
Hi, @neonnoon which repo would be contributed?

**Comment by neonnoon** [comment]
Sorry for the misleading issue description, @zhyd1997 . We have been experimenting with this during a hackathon. This is just a test repository and issue. I will make sure to delete those in the near future.
